### ISSUE TITLE
Update of ApplicationInsights-JS used

### ISSUE THREAD

**Issue by tomtom44** [TrilonIO/angular-application-insights#69]
Hi,
Thank you for this easy to use module,
I'm a new user of Azure Insights, and as I was looking into Error object format to use for a better integration in Insights, I saw that you based your module on ApplicationInsights-JS.
Is it the 1.0.7 that is actually used ?
Do you plan to update this dependency ?
Thanks

**Comment by MarkPieszak** [comment]
We're using the latest right now ^1.0.7 will point up to 1.0.9 (which is the latest types. Is there something else that was missing or needed updating, I can take a look if so!! @tomtom44

**Comment by tomtom44** [comment]
Thanks for your answer
I'm refering to this :
https://github.com/Microsoft/ApplicationInsights-JS/releases
I guess I'm wrong because there are way more recent than 1.0.9

**Comment by MarkPieszak** [comment]
Oh sorry yes we're using the latest 1.0.20 now - when you install this package, it has uses the `^` caret, so it grabs whatever the latest one is within that same major version.

The 2.x versions are still in Beta so they're unavailable at the moment but i'll make sure to upgrade to them when they come out! :)

We should be all set otherwise though, its set to ^1.0.20 just incase!
